Algoritmo sin_titulo
	Definir PRECIO_GASOLINA, GALONES_A_LITROS, GALONES_SURTIDOS COMO REAL;
	
	Escribir " INTRODUCE LOS GALORES SURTIDOS ";
	LEER GALONES_SURTIDOS;
	
	GALONES_A_LITROS = GALONES_SURTIDOS * 3.78541;
	PRECIO_GASOLINA = GALONES_A_LITROS * 1.333;
	
	Escribir " EL PRECIO QUE SE COBRA AL CLIENTE ES ", PRECIO_GASOLINA, " EUROS";
	
FinAlgoritmo




