Algoritmo sin_titulo
	DEFINIR BASE, ALTURA, SUPERFICIE, PERIMETRO Como Real;
	
	Escribir  " INTRODUCIR BASE ";
	LEER BASE;
	ESCRIBIR " INTRODUCIR ALTURA ";
	LEER ALTURA;
	
	SUPERFICIE = BASE * ALTURA;
	PERIMETRO = 2 * (BASE + ALTURA);
	Escribir "LA SUPERFICIE ES ", SUPERFICIE, " Y EL PERIMETRO ES ", PERIMETRO;
	
FinAlgoritmo

